#!/bin/sh

### BEGIN INIT INFO
# Provides:          cray-msr
# Required-Start:
# Required-Stop:
# Default-Start:     3
# Default-Stop:      0 1 2 5 6
# Description:       Provide unprivileged r/w access to specific MSRs
### END INIT INFO
PATH=/bin:/usr/bin:/usr/sbin:/sbin

case "$1" in
    start)
	modprobe cmsr ;;
    stop)
	rmmod cmsr ;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac
